name = "backend"
compatibility_date = "2024-09-11"
# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMGIxZGFjYmUtN2E3ZS00YjFkLWIxZjktYjQ0NDdlYTU0ZmU2IiwidGVuYW50X2lkIjoiOGMwZjViNzhhOWFlMWI0ODY3OTY3N2ExMmJiMzU0Njg5Y2ZlNjkxZTAwMjcwYzljMDY0YTk2NjhiZDY1Zjg4NCIsImludGVybmFsX3NlY3JldCI6IjI3ZjBiNGU5LTZhNmYtNDYwYy04MTdhLTk4MTE5MTgwZDY4MyJ9.phQZGpjUjLbExE8lFxpJTPEyH5ct_zY65c6sr9C3ML0"

JWT_SECRET="mohit123"